format = """
$username\
$hostname\
\
$directory\
\
$git_branch\
$git_state\
$git_status\
$character"""

[directory]
style = "#00FFFF"

[character]
success_symbol = "[](#00FF00)"
error_symbol = "[](#FF0000)"
vimcmd_symbol = "[](#00FFFF)"

[git_branch]
format = "[$branch]($style)"
style = "#FF0000"

[git_status]
#format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
format = "[[($modified)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = ""
untracked = " "
modified = "*"
staged = " "
renamed = " "
deleted = " "
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
disabled = true

